import { BrainCircuit, CheckCircle2, AlertTriangle, Info } from 'lucide-react';

export const AIAnalysis = () => {
  return (
    <div className="bg-white border border-border rounded-xl shadow-sm flex flex-col">
      <div className="px-6 py-4 border-b border-border flex items-center gap-3 bg-indigo-50 rounded-t-xl">
        <div className="h-9 w-9 rounded-lg bg-indigo-100 flex items-center justify-center">
          <BrainCircuit className="h-5 w-5 text-indigo-600" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-foreground">AI Market Report</h3>
          <p className="text-xs text-indigo-600">Generated by Confluence Portfolio Manager</p>
        </div>
      </div>

      <div className="p-6 space-y-5">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { label: 'Ticker', value: 'RELIANCE.NS', color: 'text-foreground' },
            { label: 'Regime', value: 'Bullish', color: 'text-emerald-600' },
            { label: 'Risk', value: 'Medium', color: 'text-amber-500' },
            { label: 'Confidence', value: '72%', color: 'text-indigo-600' },
          ].map((s) => (
            <div key={s.label} className="bg-slate-50 rounded-lg p-3 border border-border text-center">
              <p className="text-xs text-muted-foreground mb-1">{s.label}</p>
              <p className={`text-base font-bold ${s.color}`}>{s.value}</p>
            </div>
          ))}
        </div>

        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-600 mb-2 flex items-center gap-1.5">
            <CheckCircle2 className="h-3.5 w-3.5" /> Supporting Evidence
          </h4>
          <ul className="space-y-1.5">
            {['Positive technical momentum across key moving averages.', 'Increasing volume confirming the recent breakout.', 'Highly positive news sentiment over the last 24h.'].map((e, i) => (
              <li key={i} className="text-sm text-slate-600 flex items-start gap-2">
                <span className="text-emerald-500 font-bold mt-0.5">✓</span>{e}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-red-500 mb-2 flex items-center gap-1.5">
            <AlertTriangle className="h-3.5 w-3.5" /> Risk Factors
          </h4>
          <ul className="space-y-1.5">
            {['Major resistance approaching at current price level.', 'Elevated volatility in the broader sector.'].map((r, i) => (
              <li key={i} className="text-sm text-slate-600 flex items-start gap-2">
                <span className="text-red-400 font-bold mt-0.5">⚠</span>{r}
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-blue-50 border border-blue-100 rounded-lg p-4">
          <h4 className="text-xs font-bold text-blue-700 mb-1 flex items-center gap-1.5">
            <Info className="h-3.5 w-3.5" /> Invalidation Condition
          </h4>
          <p className="text-sm text-slate-600 leading-relaxed">
            "Reassess the bullish thesis if price breaks and closes below the support level at ₹2,850 on high volume."
          </p>
        </div>
      </div>
    </div>
  );
};
