import { Link } from 'react-router-dom';
import { Layers, ArrowLeft, FileText, AlertTriangle, ShieldCheck, HelpCircle } from 'lucide-react';
import logoImg from '@/assets/logo.png';

export function TermsPage() {
  const lastUpdated = 'September 23, 2026';

  return (
    <div className="min-h-screen bg-[#fafbfc] text-slate-900 font-sans selection:bg-indigo-100 selection:text-indigo-900">
      {/* Top App Bar */}
      <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-200/80">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5">
            <img src={logoImg} alt="TradeVault Logo" className="h-8 w-auto object-contain rounded-lg" />
            <span className="font-bold text-base text-slate-900 tracking-tight">TradeVault</span>
          </Link>

          <Link
            to="/"
            className="flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-indigo-600 bg-slate-50 border border-slate-200 px-3 py-1.5 rounded-full transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            <span>Back to Home</span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        {/* Document Header Card */}
        <div className="bg-white border border-slate-200/90 rounded-3xl p-8 sm:p-10 m3-elevation-1 mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 border border-indigo-200/70 text-xs font-bold text-indigo-700 uppercase tracking-wider mb-4">
            <FileText className="h-3.5 w-3.5 text-indigo-600" />
            <span>Terms of Service Agreement</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
            Terms of Service
          </h1>
          <p className="mt-3 text-slate-600 text-sm sm:text-base leading-relaxed">
            Please review these Terms of Service carefully before utilizing the TradeVault multi-agent algorithmic platform, quantitative factor models, or broker routing interfaces.
          </p>
          <div className="mt-6 pt-6 border-t border-slate-100 flex flex-wrap items-center justify-between gap-4 text-xs text-slate-400">
            <span>Last Updated: <strong>{lastUpdated}</strong></span>
            <span>Document ID: <strong>TX-TOS-2026.09</strong></span>
          </div>
        </div>

        {/* Financial Risk Notice Box */}
        <div className="bg-amber-50/70 border border-amber-200/90 rounded-3xl p-6 sm:p-8 mb-10 text-amber-950 flex items-start gap-4">
          <AlertTriangle className="h-6 w-6 text-amber-600 shrink-0 mt-1" />
          <div className="space-y-2 text-xs sm:text-sm leading-relaxed">
            <p className="font-bold text-base text-amber-900">Important Financial & Investment Disclaimer</p>
            <p>
              TradeVault is a quantitative research, backtesting, and algorithmic modeling simulation platform. TradeVault is <strong>not</strong> an investment advisor, registered broker-dealer, or financial intermediary under applicable securities regulations.
            </p>
            <p>
              All agent outputs, debate transcripts, consensus metrics, and probabilistic quantile forecasts are generated by machine learning models and quantitative statistical formulas for research purposes only, and must not be construed as investment, legal, or tax advice.
            </p>
          </div>
        </div>

        {/* Terms Body */}
        <div className="bg-white border border-slate-200/90 rounded-3xl p-8 sm:p-12 m3-elevation-1 space-y-10 text-slate-700 leading-relaxed text-sm sm:text-base">
          {/* Section 1 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">1</span>
              <h2>Acceptance of Terms</h2>
            </div>
            <p>
              By accessing, browsing, registering an account, or interacting with the TradeVault platform, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you do not accept these terms in their entirety, you must discontinue use of the platform immediately.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">2</span>
              <h2>Paper Sandbox Default & Risk of Capital Loss</h2>
            </div>
            <p>
              All newly registered TradeVault accounts default strictly to a virtual paper trading sandbox environment. No actual currency is exchanged, and no real capital is risked during sandbox execution.
            </p>
            <p>
              If you consciously choose to enable live broker execution (requiring explicit environment activation, valid live API keys, and timed confirmation phrases), you acknowledge that trading securities, equities, and derivative contracts involves substantial risk of loss, including the potential loss of all invested capital.
            </p>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">3</span>
              <h2>Multi-Agent AI Generative Outputs & Probabilistic Predictions</h2>
            </div>
            <p>
              TradeVault incorporates multi-model debate architectures (including Groq, Google Gemini, Mistral, and NVIDIA models). Generative AI systems are probabilistic by nature and can produce erroneous, incomplete, or unexpected conclusions.
            </p>
            <p>
              Past statistical backtest performance, Deflated Sharpe Ratios (DSR), and Probability of Backtest Overfitting (PBO) scores do not guarantee future market returns. You bear sole responsibility for verifying any quantitative proposal prior to execution.
            </p>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">4</span>
              <h2>Risk Manager Veto & Automated Guardrails</h2>
            </div>
            <p>
              TradeVault features automated mathematical safety checks, including the Deflated Sharpe Overfitting Gate, fractional Kelly lot sizing caps, and the Emergency Kill Switch.
            </p>
            <p>
              The platform reserves the right to automatically veto, modify, or cancel trade orders if risk boundaries or volatility limits are exceeded. TradeVault is not liable for missed market opportunities resulting from automated risk vetoes or kill-switch engagements.
            </p>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">5</span>
              <h2>Account Security & API Key Custody</h2>
            </div>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials. Any external broker API keys you submit are encrypted via AES-256-GCM. You agree to immediately notify TradeVault administrators of any suspected unauthorized access or compromise.
            </p>
          </section>

          {/* Section 6 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">6</span>
              <h2>Limitation of Liability</h2>
            </div>
            <p>
              To the fullest extent permitted by applicable law, TradeVault, its contributors, affiliates, and developers shall not be liable for any direct, indirect, incidental, punitive, or consequential damages resulting from:
            </p>
            <ul className="list-disc pl-6 space-y-1.5 text-slate-600">
              <li>Trading losses, slippage, or exchange-level execution failures.</li>
              <li>Broker connectivity interruptions, API rate limits, or network latency.</li>
              <li>Errors, inaccuracies, or hallucinations in multi-agent LLM debate transcripts.</li>
              <li>Unforeseen server downtime, maintenance periods, or emergency kill-switch halts.</li>
            </ul>
          </section>

          {/* Section 7 */}
          <section className="space-y-3 pt-4 border-t border-slate-100">
            <div className="flex items-center gap-2.5 text-slate-900 font-bold text-lg">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 text-xs font-black">7</span>
              <h2>Questions & Support</h2>
            </div>
            <p className="text-slate-600">
              If you have inquiries regarding these Terms of Service, contact our administrative team at{' '}
              <a href="mailto:support@tradevault.local" className="text-indigo-600 font-semibold hover:underline">
                support@tradevault.local
              </a>.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-xs text-slate-400">
          <p>© 2026 TradeVault. All rights reserved. Quantitative algorithmic advisory & execution engine.</p>
        </div>
      </main>
    </div>
  );
}
